server:
  port: 8084

spring:
  application:
    name: job-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27020/job_db}
      auto-index-creation: true

security:
  api-key: job-service-secret-key-12345
