server:
  port: 8083

spring:
  application:
    name: company-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://${DB_HOST:localhost}:${DB_PORT:27019}/company_db}
      auto-index-creation: true

security:
  api-key: company-service-secret-key-12345
